app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(`plot-depth` = 390)
app$setInputs(`plot-depth` = 1141)
app$setInputs(`plot-depth` = 1482)
app$setInputs(`plot-depth` = 1970)
app$snapshot()
app$setInputs(`plot-depth` = 1429)
app$snapshot()
app$setInputs(`plot-depth` = 785)
app$snapshot()
app$setInputs(`plot-depth` = 239)
app$snapshot()
