app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(`NOAA-go` = "click")
app$snapshot()
app$setInputs(`NOAA-var` = "phosphate")
app$setInputs(`NOAA-go` = "click")
app$snapshot()
app$setInputs(`NOAA-var` = "nitrate")
app$setInputs(`NOAA-go` = "click")
app$snapshot()
app$setInputs(`NOAA-var` = "silicate")
app$setInputs(`NOAA-go` = "click")
app$snapshot()
