app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(`NOAA-go` = "click")
app$snapshot()
app$snapshot()
app$setInputs(`worldmap-depth` = 335)
app$setInputs(`depth-back` = "click")
app$snapshot()
app$snapshot()
app$setInputs(`depth-back` = "click")
app$snapshot()
app$setInputs(`depth-reset` = "click")
app$snapshot()
