app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(`NOAA-go` = "click")
app$snapshot()
app$setInputs(`worldmap-depth` = 222)
app$snapshot()
app$snapshotDownload("download-download")
app$snapshot()
