app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(`filter-depth` = "1")
app$setInputs(`filter-lat` = "33")
app$setInputs(`filter-lon` = "-")
app$setInputs(`filter-lon` = "-1450")
app$setInputs(`filter-lon` = "-145")
app$setInputs(`filter-extract` = "click")
app$snapshot()
app$setInputs(`filter-lat` = "3")
app$setInputs(`filter-lat` = "")
app$setInputs(`filter-lat` = "-33")
app$setInputs(`filter-extract` = "click")
app$snapshot()
app$setInputs(`filter-back` = "click")
app$snapshot()
app$setInputs(`filter-reset` = "click")
