# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]

name: shiny-deploy

jobs:
  shiny-deploy:
    runs-on: ubuntu-22.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnetcdf-dev libudunits2-dev libgdal-dev libgeos-dev libproj-dev libfontconfig1-dev

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rsconnect, any::pkgload
          needs: deployment

      - name: Deploy to ShinyApps
        env:
          RSCONNECT_USER: ${{ secrets.RSCONNECT_USER }}
          RSCONNECT_TOKEN: ${{ secrets.RSCONNECT_TOKEN }}
          RSCONNECT_SECRET: ${{ secrets.RSCONNECT_SECRET }}
        run: |
          rsconnect::setAccountInfo(
            Sys.getenv("RSCONNECT_USER"),
            Sys.getenv("RSCONNECT_TOKEN"),
            Sys.getenv("RSCONNECT_SECRET")
          )
          file.copy("inst/appdir/app.R", ".", overwrite = TRUE)
          rsconnect::deployApp(
            appName = "oceanexplorer",
            account = "martinschobben",
            server = "shinyapps.io",
            appFiles = setdiff(list.files(), c('.Rprofile', 'renv', 'README.Rmd', 'renv.lock')),
            forceUpdate = TRUE
          )
        shell: Rscript {0}